version: "3.7"
services:
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: randompassword
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      # - ./apps/api/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql